### PR TITLE
Implement tests with ava, nyc and codecov 

### PR DESCRIPTION
**Pull request by SavageCore**
This is a WIP PR implementing tests with ava. A couple of tasks are needed by the repo owner to complete:

Enable the repo at 
- [x] [travis-ci](https://travis-ci.org)
- [x] [codecov](https://codecov.io/)
- [x] update `package.json` scripts test to `nyc ava && nyc report --reporter=text-lcov > coverage.lcov && codecov -t TOKEN`

### Some thougths:

Have I missed any test cases? 

Unnecessary given the simplicity of this plugin?

### CODE REVIEW

**Comment by miniyarov** [comment]
Thank you for the PR.
Given the simplicity of plugin I did not implement any tests. I will configure travis-ci and codecov to support your PR.

**Comment by SavageCore** [comment]
@miniyarov Great, what is the token for codecov? I will update the test script in package. Should be able to merge once that is done.

**Comment by miniyarov** [comment]
@SavageCore I guess it can be sent publicly: 1f44ab6ec-8c63-4adb-8795-eb8386870765

**Comment by SavageCore** [comment]
@miniyarov Thanks, yeah they aren't secret, in fact turns out for public repos they aren't even needed.

> The upload token is required for all uploads, except originating from public project using Travis-CI, Circle CI, or AppVeyor CI.

https://docs.codecov.io/docs/frequently-asked-questions#section-where-is-the-repository-upload-token-found-

**Comment by miniyarov** [comment]
@SavageCore Thanks for the good work 👍

**Pull request merged**
